
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchUniversityService", targetNamespace = "http://WebService/", wsdlLocation = "http://localhost:8888/WebService?wsdl")
public class SearchUniversityService
    extends Service
{

    private final static URL SEARCHUNIVERSITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHUNIVERSITYSERVICE_EXCEPTION;
    private final static QName SEARCHUNIVERSITYSERVICE_QNAME = new QName("http://WebService/", "SearchUniversityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHUNIVERSITYSERVICE_WSDL_LOCATION = url;
        SEARCHUNIVERSITYSERVICE_EXCEPTION = e;
    }

    public SearchUniversityService() {
        super(__getWsdlLocation(), SEARCHUNIVERSITYSERVICE_QNAME);
    }

    public SearchUniversityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHUNIVERSITYSERVICE_QNAME, features);
    }

    public SearchUniversityService(URL wsdlLocation) {
        super(wsdlLocation, SEARCHUNIVERSITYSERVICE_QNAME);
    }

    public SearchUniversityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHUNIVERSITYSERVICE_QNAME, features);
    }

    public SearchUniversityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchUniversityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchUniversity
     */
    @WebEndpoint(name = "SearchUniversityPort")
    public SearchUniversity getSearchUniversityPort() {
        return super.getPort(new QName("http://WebService/", "SearchUniversityPort"), SearchUniversity.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchUniversity
     */
    @WebEndpoint(name = "SearchUniversityPort")
    public SearchUniversity getSearchUniversityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebService/", "SearchUniversityPort"), SearchUniversity.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHUNIVERSITYSERVICE_EXCEPTION!= null) {
            throw SEARCHUNIVERSITYSERVICE_EXCEPTION;
        }
        return SEARCHUNIVERSITYSERVICE_WSDL_LOCATION;
    }

}
